#!/usr/bin/env python3
# Single generator: markets.json (the multi-package source of truth) -> everything downstream.
# Each market entry is self-contained (carries its OWN coinType/mintTarget/cap/pkg), so markets
# can live across ANY number of coin packages — adding a market never touches existing packages.
# Writes: app/web/src/markets.ts, app/sui-harness/registry.json, app/sui-harness/faucet.json
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
d = json.load(open(os.path.join(HERE, "markets.json")))
stable, markets = d["stable"], d["markets"]

def coin_type(m): return m.get("coinType") or f'{m["pkg"]}::{m["module"]}::{m["struct"]}'
def mint_target(m): return m.get("mintTarget") or f'{m["pkg"]}::{m["module"]}::mint'

# --- web markets.ts (literal coinTypes; no shared-package assumption) ---
rows = []
for m in markets:
    rows.append(
        f'  {{ symbol: "{m["sym"]}", name: "{m["name"]}", coinType: "{coin_type(m)}", '
        f'decimals: {m["decimals"]}, feedId: "{m["feedId"]}", ltvBps: {m["ltvBps"]}, '
        f'liqBps: {m["liqBps"]}, assetClass: "{m["assetClass"]}", gap: {str(m.get("gap", False)).lower()} }},'
    )
ts = '''// GENERATED by app/sui-harness/gen-configs.py from markets.json — do not edit by hand.
// The markets the app supports — the xStocks catalog (tokenized US large-caps + major ETFs) plus
// core crypto. Each is a collateral Coin on Sui (test tokens on devnet) priced by a real Pyth feed,
// self-describing its full coinType so markets can span multiple coin packages.
export interface Market {
  symbol: string; name: string; coinType: string; decimals: number;
  feedId: string; ltvBps: number; liqBps: number; assetClass: "crypto" | "equity"; gap: boolean;
}

export const MARKETS: Market[] = [
''' + "\n".join(rows) + '''
];

export const marketByCoinType = (coinType: string) => MARKETS.find((m) => m.coinType === coinType);

/** hi-3 mono chip label. */
export const chip = (s: string) => s.replace(/x$/, "").slice(0, 3).toUpperCase();
'''
open(os.path.join(ROOT, "web/src/markets.ts"), "w").write(ts)

# --- operator registry (server owns feed/ltv/decimals/assetClass, keyed by full coinType) ---
reg = {coin_type(m): {"feedId": m["feedId"], "ltvBps": m["ltvBps"], "decimals": m["decimals"], "assetClass": m["assetClass"]} for m in markets}
json.dump(reg, open(os.path.join(HERE, "registry.json"), "w"))

# --- faucet: stable first, then every collateral (server mints stable + the requested one) ---
fau = [{"target": stable["mintTarget"], "cap": stable["cap"], "amount": stable["faucetAmount"]}]
fau += [{"target": mint_target(m), "cap": m["cap"], "amount": m["faucetAmount"]} for m in markets]
json.dump(fau, open(os.path.join(HERE, "faucet.json"), "w"))

print(f"generated: {len(markets)} markets -> web/src/markets.ts, registry.json, faucet.json")
