// Generate src/docs.generated.ts from the repo docs so the site can render them (self-contained).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const DOCS = join(HERE, "..", "..", "docs");

// visitor-facing docs (skip internal planning docs)
const PICK = [
  ["WHY-ASSAY-IS-DIFFERENT.md", "Why Assay is different", "How our lending differs from Aave/Kamino/Suilend — and why it's safer, in plain terms."],
  ["INTEREST-RATE-MODEL.md", "Interest rate model", "How supply/borrow rates are set by utilization to attract liquidity."],
  ["LTV-RISK-FRAMEWORK.md", "LTV & risk framework", "How loan-to-value limits are chosen per asset from a stress model."],
  ["AUDIT-2026-07-14-sui.md", "Security audit & pentest", "Adversarial review + penetration test — one critical bug found and fixed."],
  ["EVIDENCE-2026-07-14.md", "Evidence", "On-chain proofs, the penetration test, and full end-to-end loans."],
  ["ARCHITECTURE.md", "Architecture", "The four tiers: frontend, operator, on-chain program, and oracle."],
];

const docs = PICK.map(([file, title, desc]) => {
  let md = "";
  try { md = readFileSync(join(DOCS, file), "utf8"); } catch { md = `# ${title}\n\n_(document unavailable)_`; }
  const slug = file.replace(/\.md$/, "").toLowerCase();
  return { slug, title, desc, md };
});

const out = `// GENERATED by gen-docs.mjs — do not edit by hand.
export interface Doc { slug: string; title: string; desc: string; md: string }
export const DOCS: Doc[] = ${JSON.stringify(docs, null, 0)};
`;
writeFileSync(join(HERE, "src", "docs.generated.ts"), out);
console.log(`generated src/docs.generated.ts — ${docs.length} docs`);
